Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using WebShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Http;

namespace WebShop.Pages
{
    public class IndexModel : PageModel
    {
        private readonly WebDBContext _database;
        public Product[] mas { get; set; }
        public IndexModel(WebDBContext database)
        {
            _database = database;
        }

        public void OnGet(int genreId)
        {
            if (genreId != 0)
            {
                var temp = _database.ProductGenre.Where(x => x.IdGenre == genreId);
                mas = _database.Product.Join(temp, p => p.Id, c => c.IdProduct, (p, c) => new Product() { Id = p.Id, Name = p.Name, Cost = p.Cost, Quantity = p.Quantity, Description = p.Description, IconUrl = p.IconUrl, PictureUrl = p.PictureUrl, IdDeveloper = p.IdDeveloper, IdPublisher = p.IdPublisher }).ToArray();
            }
            else
            {
                mas = _database.Product.ToArray();
            }
            if (User.Identity.IsAuthenticated)
            {
                if (_database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault().Id == 1)
                {
                    HttpContext.Session.SetString("IsRole", "Admin");
                }
                else
                {
                    HttpContext.Session.SetString("IsRole", "User");
                }
            }
            else
            {
                HttpContext.Session.SetString("IsRole", "Guest");
            }
        }

        public void OnGetRand()
        {
            mas = _database.Product.ToArray();
            mas = RandList(mas);

            var len = new Random().Next(1, mas.Length - 1);
            Product[] temp = new Product[len];
            Array.Copy(mas, 0, temp, 0, len);
            mas = new Product[len];
            Array.Copy(temp, mas, len);

        }

        public Product[] RandList(Product[] products)
        {
            for (int i = products.Length - 1; i >= 1; i--)
            {
                int j = new Random().Next(i + 1);
                // обменять значения data[j] и data[i]
                var temp = products[j];
                products[j] = products[i];
                products[i] = temp;
            }
            return products;
        } 

        public void OnPostSearch(string search)
        {
            //var temp = _database.Product.Where(x => x.Name == search);
            var temp_name = _database.Product.Where(p => EF.Functions.Like(p.Name, "%" +search+"%"));
            var temp_description = _database.Product.Where(p => EF.Functions.Like(p.Description, "%" + search + "%"));
            mas = temp_name.Union(temp_description).ToArray().Distinct().ToArray();
            //mas = _database.Product.Join(temp, p => p.Id, c => c.Id, (p, c) => new Product() { Id = p.Id, Name = p.Name, Cost = p.Cost, Quantity = p.Quantity, Description = p.Description, IconUrl = p.IconUrl, PictureUrl = p.PictureUrl, IdDeveloper = p.IdDeveloper, IdPublisher = p.IdPublisher }).ToArray();
        }

        public void OnGetAddBasket(int id)
        {
            int userId = _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault().Id;
            _database.Basket.Add(new Basket { IdProduct = (short)id, IdUser = userId, Status = 1 });
            _database.SaveChanges();
            mas = _database.Product.ToArray();
        }

        public bool InBasket(int id)
        {
            int userId = _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault().Id;
            if (_database.Basket.Where(x => x.IdUser == userId && x.IdProduct == id).FirstOrDefault() == null)
            {
                return false;
            }
            return true;
        }

        public void OnGetDelBasket(int id)
        {
            int userId = _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault().Id;
            _database.Basket.Remove(_database.Basket.Where(x => x.IdUser == userId && x.IdProduct == id).FirstOrDefault());
            _database.SaveChanges();
            mas = _database.Product.ToArray();
        }

        public string GetUserName()
        {
            return _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault().Name;
        }

    }
}

Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using WebShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;

namespace WebShop
{
    [ValidateAntiForgeryToken]
    public class LoginModel : PageModel
    {
        private readonly WebDBContext _database;
        public LoginModel(WebDBContext database)
        {
            _database = database;
        }


        [Required(ErrorMessage = "Не указан Email")]
        [BindProperty]
        [DataType(DataType.EmailAddress)]
        public string EMail { get; set; }

        [Required(ErrorMessage = "Не указан пароль")]
        [DataType(DataType.Password)]
        [BindProperty]
        public string Password { get; set; }

        public IActionResult OnPostLogin()
        {
            if (ModelState.IsValid)
            {
                User user = _database.User.FirstOrDefault(u => u.EMail == EMail && u.Password == Password);
                if (user != null)
                {
                    Authenticate(EMail); // аутентификация  
                }
                else
                {
                    ModelState.AddModelError("", "Некорректные логин и(или) пароль");
                    return RedirectToPage("/Login");
                }
                return RedirectToPage("/Index");
            }
            else
            {
                ModelState.AddModelError("", "Некорректные логин и(или) пароль");
                return RedirectToPage("/Login");
            }
        }
        public void OnGet()
        {
            
        }

        private Task Authenticate(string userName)
        {
            // создаем один claim
            var claims = new List<Claim>
            {
                new Claim(ClaimsIdentity.DefaultNameClaimType, userName)
            };
            // создаем объект ClaimsIdentity
            ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType, ClaimsIdentity.DefaultRoleClaimType);
            // установка аутентификационных куки
            return HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }

        public IActionResult OnGetLogout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("/Index");
        }

    }
}

Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Game Shop</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/top-menu.css">
    <link rel="stylesheet" href="~/css/search-field.css">
    <link rel="stylesheet" href="~/css/main-field.css">
    @RenderSection("Imports", false)
</head>

<body>
    <div class="all">
        <div class="top">
            <div class="top-container">
                <a asp-area="" asp-page="/Index" style="color: white"><div class="logo">Game Shop</div></a>
                <div class="page-name">@RenderSection("Page", false)</div>
                <div class="basket-button"><a href="/Basket"><div class="basket-icon" style="background-image: url(/img/basket.png)"></div></a></div>
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="dropdown">
                        <div class="profile-button"><a href="/Profile"><div class="profile-icon" style="background-image: url(/img/profile.png)"></div></a></div>

                        <div class="dropdown-content">
                            <a>@RenderSection("MyName", false)</a>
                            <a asp-page="/Profile">Профиль</a>
                            @if (Context.Session.GetString("IsRole") != null)
                            {
                                var isRole = Context.Session.GetString("IsRole");
                                if (isRole == "Admin")
                                {
                                    <a asp-page="/Admin">Админ-панель</a>
                                }
                            }
                            <a asp-page="/Login" asp-page-handler="Logout">Выход</a>
                        </div>
                    </div>
                }
                else
                {
                    IgnoreSection("MyName");
                    <div class="profile-button"><a href="/Login"><div class="profile-icon" style="background-image: url(/img/profile.png)"></div></a></div>
                }
            </div>
            <div class="bottom-container">
                <div class="search">
                    <form method="POST">
                        <input type="text" name="search" placeholder="Искать здесь..." />
                        <button type="submit" asp-page="/Index" asp-page-handler="Search"><div class="search-icon" style="background-image: url(/img/search.png)"></div></button>
                    </form>
                </div>
            </div>
        </div>
        <div class="main">
            @RenderBody()
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>