Pages/Admin.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebShop.Models;
using Microsoft.AspNetCore.Authorization;

namespace WebShop
{
    [Authorize]
    public class AdminModel : PageModel
    {
        private readonly WebDBContext _database;

        public User[] Users;
        public Product[] Products;
        public Dictionary<int, string> Developers = new Dictionary<int, string>();

        public Dictionary<int, string> Publishers = new Dictionary<int, string>();
        public AdminModel(WebDBContext database)
        {
            _database = database;
        }

        public string _desc { get; set; }

        public void OnGet(string desc)
        {
            Users = _database.User.ToArray();
            Products = _database.Product.ToArray();
            var _developers = _database.Developer.ToArray();
            var _publisher = _database.Publisher.ToArray();
            foreach (var e in _developers)
            {
                Developers.Add(e.Id, e.Name);
            }
            foreach (var e in _publisher)
            {
                Publishers.Add(e.Id, e.Name);
            }
            _desc = desc;
        }

        public string GetUserName()
        {
            return _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault().Name;
        }

        public void OnGetDeleteUser(int id)
        {
            User user = _database.User.Where(x => x.Id == id).FirstOrDefault();
            _database.Remove(user);
            _database.SaveChanges();
            OnGet("users");
        }

        public void OnGetDeleteProduct(int id)
        {
            Product product = _database.Product.Where(x => x.Id == id).FirstOrDefault();
            _database.Remove(product);
            _database.SaveChanges();
            OnGet("products");
        }

    }
}

Pages/Basket.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebShop.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace WebShop
{
    [Authorize]
    public class BasketModel : PageModel
    {
        private readonly WebDBContext _database;
        public Product[] mas { get; set; }
        public BasketModel(WebDBContext database)
        {
            _database = database;
        }
        public void OnGet()
        {
            int userId = _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault().Id;
            var temp = _database.Basket.Where(x => x.IdUser == userId);
            mas = _database.Product.Join(temp, p => p.Id, c => c.IdProduct, (p, c) => new Product() { Id = p.Id, Name = p.Name, Cost = p.Cost, Quantity = p.Quantity, Description = p.Description, IconUrl = p.IconUrl, PictureUrl = p.PictureUrl, IdDeveloper = p.IdDeveloper, IdPublisher = p.IdPublisher }).ToArray();
        }

        public void OnGetDelBasket(int id)
        {
            int userId = _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault().Id;
            _database.Basket.Remove(_database.Basket.Where(x => x.IdUser == userId && x.IdProduct == id).FirstOrDefault());
            _database.SaveChanges();
            var temp = _database.Basket.Where(x => x.IdUser == userId);
            mas = _database.Product.Join(temp, p => p.Id, c => c.IdProduct, (p, c) => new Product() { Id = p.Id, Name = p.Name, Cost = p.Cost, Quantity = p.Quantity, Description = p.Description, IconUrl = p.IconUrl, PictureUrl = p.PictureUrl, IdDeveloper = p.IdDeveloper, IdPublisher = p.IdPublisher }).ToArray();
        }

        public string GetUserName()
        {
            return _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault().Name;
        }

    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using WebShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Session;
using Microsoft.AspNetCore.Http;

namespace WebShop.Pages
{
    public class IndexModel : PageModel
    {
        private readonly WebDBContext _database;
        public Product[] mas { get; set; }
        public IndexModel(WebDBContext database)
        {
            _database = database;
        }

        public void OnGet(int genreId)
        {
            if (genreId != 0)
            {
                var temp = _database.ProductGenre.Where(x => x.IdGenre == genreId);
                mas = _database.Product.Join(temp, p => p.Id, c => c.IdProduct, (p, c) => new Product() { Id = p.Id, Name = p.Name, Cost = p.Cost, Quantity = p.Quantity, Description = p.Description, IconUrl = p.IconUrl, PictureUrl = p.PictureUrl, IdDeveloper = p.IdDeveloper, IdPublisher = p.IdPublisher }).ToArray();
            }
            else
            {
                mas = _database.Product.ToArray();
            }
            if (User.Identity.IsAuthenticated)
            {
                if (_database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault().Id == 1)
                {
                    HttpContext.Session.SetString("IsRole", "Admin");
                }
                else
                {
                    HttpContext.Session.SetString("IsRole", "User");
                }
            }
            else
            {
                HttpContext.Session.SetString("IsRole", "Guest");
            }
        }

        public void OnGetRand()
        {
            mas = _database.Product.ToArray();
            mas = RandList(mas);

            var len = new Random().Next(1, mas.Length - 1);
            Product[] temp = new Product[len];
            Array.Copy(mas, 0, temp, 0, len);
            mas = new Product[len];
            Array.Copy(temp, mas, len);

        }

        public Product[] RandList(Product[] products)
        {
            for (int i = products.Length - 1; i >= 1; i--)
            {
                int j = new Random().Next(i + 1);
                // обменять значения data[j] и data[i]
                var temp = products[j];
                products[j] = products[i];
                products[i] = temp;
            }
            return products;
        } 

        public void OnPostSearch(string search)
        {
            //var temp = _database.Product.Where(x => x.Name == search);
            var temp_name = _database.Product.Where(p => EF.Functions.Like(p.Name, "%" +search+"%"));
            var temp_description = _database.Product.Where(p => EF.Functions.Like(p.Description, "%" + search + "%"));
            mas = temp_name.Union(temp_description).ToArray().Distinct().ToArray();
            //mas = _database.Product.Join(temp, p => p.Id, c => c.Id, (p, c) => new Product() { Id = p.Id, Name = p.Name, Cost = p.Cost, Quantity = p.Quantity, Description = p.Description, IconUrl = p.IconUrl, PictureUrl = p.PictureUrl, IdDeveloper = p.IdDeveloper, IdPublisher = p.IdPublisher }).ToArray();
        }

        public void OnGetAddBasket(int id)
        {
            int userId = _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault().Id;
            _database.Basket.Add(new Basket { IdProduct = (short)id, IdUser = userId, Status = 1 });
            _database.SaveChanges();
            mas = _database.Product.ToArray();
        }

        public bool InBasket(int id)
        {
            int userId = _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault().Id;
            if (_database.Basket.Where(x => x.IdUser == userId && x.IdProduct == id).FirstOrDefault() == null)
            {
                return false;
            }
            return true;
        }

        public void OnGetDelBasket(int id)
        {
            int userId = _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault().Id;
            _database.Basket.Remove(_database.Basket.Where(x => x.IdUser == userId && x.IdProduct == id).FirstOrDefault());
            _database.SaveChanges();
            mas = _database.Product.ToArray();
        }

        public string GetUserName()
        {
            return _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault().Name;
        }

    }
}

Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using WebShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;

namespace WebShop
{
    [ValidateAntiForgeryToken]
    public class LoginModel : PageModel
    {
        private readonly WebDBContext _database;
        public LoginModel(WebDBContext database)
        {
            _database = database;
        }


        [Required(ErrorMessage = "Не указан Email")]
        [BindProperty]
        [DataType(DataType.EmailAddress)]
        public string EMail { get; set; }

        [Required(ErrorMessage = "Не указан пароль")]
        [DataType(DataType.Password)]
        [BindProperty]
        public string Password { get; set; }

        public IActionResult OnPostLogin()
        {
            if (ModelState.IsValid)
            {
                User user = _database.User.FirstOrDefault(u => u.EMail == EMail && u.Password == Password);
                if (user != null)
                {
                    Authenticate(EMail); // аутентификация  
                }
                else
                {
                    ModelState.AddModelError("", "Некорректные логин и(или) пароль");
                    return RedirectToPage("/Login");
                }
                return RedirectToPage("/Index");
            }
            else
            {
                ModelState.AddModelError("", "Некорректные логин и(или) пароль");
                return RedirectToPage("/Login");
            }
        }
        public void OnGet()
        {
            
        }

        private Task Authenticate(string userName)
        {
            // создаем один claim
            var claims = new List<Claim>
            {
                new Claim(ClaimsIdentity.DefaultNameClaimType, userName)
            };
            // создаем объект ClaimsIdentity
            ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType, ClaimsIdentity.DefaultRoleClaimType);
            // установка аутентификационных куки
            return HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }

        public IActionResult OnGetLogout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("/Index");
        }

    }
}

Pages/Profile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebShop.Models;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;

namespace WebShop
{
    [Authorize]
    public class ProfileModel : PageModel
    {

        private WebDBContext _database;
        public Product[] mas { get; set; }
        public ProfileModel(WebDBContext database)
        {
            _database = database;
        }
        public void OnGet(int genreId)
        {
            ViewData["Title"] = GetUserName();
            if (genreId != 0)
            {
                var temp = _database.ProductGenre.Where(x => x.IdGenre == genreId);
                mas = _database.Product.Join(temp, p => p.Id, c => c.IdProduct, (p, c) => new Product() { Id = p.Id, Name = p.Name, Cost = p.Cost, Quantity = p.Quantity, Description = p.Description, IconUrl = p.IconUrl, PictureUrl = p.PictureUrl, IdDeveloper = p.IdDeveloper, IdPublisher = p.IdPublisher }).ToArray();
            }
            else
            {
                mas = _database.Product.ToArray();
            }
        }

        public string GetUserName()
        {
            return _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault().Name;
        }

        
        public void OnPostChangName(string name)
        {
            User user = _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault();
            if (name != null)
            {
                if (_database.User.Any(p => p.Name == name) == false)
                {
                    user.Name = name;
                    _database.SaveChanges();
                }
            }

        }

        public void OnPostChangEMail(string email)
        {
            ViewData["Title"] = GetUserName();
            User user = _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault();
            if (email != null)
            {
                if (_database.User.Any(p => p.EMail == email) == false)
                {
                    user.EMail = email;
                    _database.SaveChanges();
                    Authenticate(email);
                }
            }
        }

        public void OnPostChangPassword(string password, string confirmPassword)
        {

            User user = _database.User.Where(x => x.EMail == User.Identity.Name).FirstOrDefault();
            if (password == confirmPassword)
            {
                if (password != null)
                {
                    if (user.Password != password)
                    {
                        user.Password = password;
                        _database.SaveChanges();
                    }
                }
            }
        }


        private Task Authenticate(string userName)
        {
            // создаем один claim
            var claims = new List<Claim>
            {
                new Claim(ClaimsIdentity.DefaultNameClaimType, userName)
            };
            // создаем объект ClaimsIdentity
            ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType, ClaimsIdentity.DefaultRoleClaimType);
            // установка аутентификационных куки
            return HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }

    }
}

Pages/Registration.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using WebShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;

namespace WebShop
{
    public class RegistrationModel : PageModel
    {
        private readonly WebDBContext _database;

        [BindProperty]
        [Required(ErrorMessage = "Не указан Email")]
        [DataType(DataType.EmailAddress)]
        public string EMail { get; set; }

        [BindProperty]
        [Required(ErrorMessage = "Не указано имя")]
        public string Name { get; set; }

        [BindProperty]
        [Required(ErrorMessage = "Не указан пароль")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [BindProperty]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Пароль введен неверно")]
        public string ConfirmPassword { get; set; }

        public RegistrationModel(WebDBContext database)
        {
            _database = database;
        }

        public IActionResult OnPostRegister()
        {
            if (!ModelState.IsValid)
            {
                User user = _database.User.FirstOrDefault(u => u.EMail == EMail);
                int lastId = _database.User.OrderByDescending(x => x.Id).FirstOrDefault().Id;
                if (user == null)
                {
                    // добавляем пользователя в бд
                    _database.User.Add(new User { Id = lastId + 1, EMail = EMail, Name = Name, Password = Password });
                    _database.SaveChanges();

                    Authenticate(EMail); // аутентификация
                }
                else
                {
                    ModelState.AddModelError("", "Некорректные логин и(или) пароль");
                }
            }
            return RedirectToPage("/Index");
        }

        private Task Authenticate(string userName)
        {
            // создаем один claim
            var claims = new List<Claim>
            {
                new Claim(ClaimsIdentity.DefaultNameClaimType, userName)
            };
            // создаем объект ClaimsIdentity
            ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType, ClaimsIdentity.DefaultRoleClaimType);
            // установка аутентификационных куки
            return HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }

    }
}

Pages/Admin.cshtml
@page
@model WebShop.AdminModel
@{
    ViewData["Title"] = "Admin";
}

<div class="admin-container">
    <div class="admin-menu-container">
        <a asp-page="/Admin" asp-route-desc="users" style="color: white;"><div class="middle-button">Пользователи</div></a>
        <a asp-page="/Admin" asp-route-desc="products" style="color: white;"><div class="middle-button">Товары</div></a>
        <a asp-page="/Index" style="color: white;" asp-page-handler="Logout"><div class="middle-button">Вернуться на сайт</div></a>
    </div>
    <div class="admin-panel" id="admin-panel">
        <table>
            <thead>
                <tr>
                    @if (Model._desc == "users")
                    {
                        <th>Имя</th>
                        <th>Почта</th>
                        <th>Пароль</th>
                    }
                    else
                    {
                        <th></th>
                        <th>Название</th>
                        <th>Стоимость</th>
                        <th>Количество</th>
                        <th>Разработчик</th>
                        <th>Издатель</th>
                        <th></th>
                    }
                </tr>
            </thead>
            <tbody>
                @if (Model._desc == "users")
                {
                    foreach (var user in Model.Users)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => user.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => user.EMail)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => user.Password)
                            </td>
                            <td>
                                <a asp-page="/Control/EditUser" asp-route-id="@user.Id">Изменить</a> |
                                <a asp-page-handler="DeleteUser" asp-route-id="@user.Id">Удалить</a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>
                            <a asp-route-id="0" asp-page="/Control/EditProduct">Добавить</a>
                        </td>
                    </tr>
                    foreach (var product in Model.Products)
                    {
                        <tr>
                            <td>
                                <img src="@product.IconUrl" style="width: 128px; height: 128px;" />
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => product.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => product.Cost)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => product.Quantity)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => Model.Developers[(int)product.IdDeveloper])
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => Model.Publishers[(int)product.IdPublisher])
                            </td>
                            <td>                              
                                <a asp-page="/Control/EditProduct" asp-route-id="@product.Id">Изменить</a> |
                                <a asp-page-handler="DeleteProduct" asp-route-id="@product.Id">Удалить</a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
        </table>
        <br>
    </div>
</div>

@section Imports
{
    <link rel="stylesheet" href="~/css/admin.css">
    <link rel="stylesheet" href="~/css/dropdown.css">
}

@section Page
{
    Админ-панель
}

@section MyName
{
    Admin
}

Pages/Basket.cshtml
@page
@model WebShop.BasketModel
@{
    ViewData["Title"] = "Корзина";
}

<div class="profile-container">
    <div class="profile-menu-container">
        <div class="middle-button"><a asp-page="/Profile" style="color: white;">Профиль</a></div>
        <div class="middle-button"><a asp-page="/Basket" style="color: white;">Корзина</a></div>
        <div class="middle-button"><a asp-page="/Login" style="color: white;" asp-page-handler="Logout">Выход</a></div>
        <div class="middle-button">Удалить аккаунт</div>
    </div>
    <div class="profile-products">
        @foreach (var e in Model.mas)
        {
            <div class="product-container" id="product-@e.Id">
                <div class="title" id="product-@e.Id-title">@e.Name</div>
                <div class="icon" id="product-@e.Id-icon" style="background-image: url(@e.IconUrl)"></div>
                <div class="cost-container" id="product-@e.Id-cost-container">
                    <div class="cost" id="product-@e.Id-cost-container-cost"><a href="/ProductPage?id=@e.Id&desc=0" style="color: white">@e.Cost ₽</a></div>
                    <div class="buy" id="product-@e.Id-cost-container-buy"><a asp-route-id=@e.Id asp-page-handler="DelBasket" style="color: white"><div class="product-basket-icon" style="background-image: url(/img/delete.png)"></div></a></div>
                </div>
            </div>
        }
    </div>
</div>

@section Imports
{
    <link rel="stylesheet" href="~/css/product.css">
    <link rel="stylesheet" href="~/css/dropdown.css">
    <link rel="stylesheet" href="~/css/profile.css">
}

@section MyName
{
    @Model.GetUserName()
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Главная";
}

<div class="menu">
    <div class="dropdown">
        <button class="menu-dropbtn">&equiv; Каталог</button>
        <div class="dropdown-content">
            <a href="/Index">Все игры</a>
            <a href="/Index?genreId=1">Гонки</a>
            <a href="/Index?genreId=2">Приключения</a>
            <a href="/Index?genreId=3">Ролевые</a>
            <a href="/Index?genreId=4">Стратегии</a>
            <a href="/Index?genreId=5">Симуляторы</a>
            <a href="/Index?genreId=6">Экшен</a>
            <a href="/Index?genreId=7">Инди</a>
        </div>
    </div>
    <div class="small-button"><a style="color: white;" asp-page-handler="Rand">Популярное</a></div>
    <div class="small-button"><a style="color: white;" asp-page-handler="Rand">Рекомендуем</a></div>
    <div class="small-button"><a style="color: white;" asp-page-handler="Rand">Новое</a></div>
    <div class="small-button"><a style="color: white;" asp-page-handler="Rand">Скидки</a></div>
</div>
<div class="products" id="products">
    @foreach (var e in Model.mas)
    {
        <div class="product-container" id="product-@e.Id">
            <div class="title" id="product-@e.Id-title">@e.Name</div>
            <div class="icon" id="product-@e.Id-icon" style="background-image: url(@e.IconUrl)"></div>
            <div class="cost-container" id="product-@e.Id-cost-container">
                <div class="cost" id="product-@e.Id-cost-container-cost"><a href="/ProductPage?id=@e.Id&desc=0" style="color: white">@e.Cost ₽</a></div>
                @if (User.Identity.IsAuthenticated)
                {
                    if (Model.InBasket(e.Id) == false)
                    {
                        <div class="buy" id="product-@e.Id-cost-container-buy"><a asp-route-id=@e.Id asp-page-handler="AddBasket" style="color: white"><div class="product-basket-icon" style="background-image: url(/img/basket.png)"></div></a></div>
                    }
                    else
                    {
                        <div class="buy" id="product-@e.Id-cost-container-buy"><a asp-route-id=@e.Id asp-page-handler="DelBasket" style="color: white"><div class="product-basket-icon" style="background-image: url(/img/delete.png)"></div></a></div>
                    }
                }
            </div>
        </div>
    }
</div>

@section Imports
{
    <link rel="stylesheet" href="~/css/product.css">
    <link rel="stylesheet" href="~/css/dropdown.css">
}

@section Page
{
    Главная
}

@section MyName
{
    @Model.GetUserName()
}

Pages/Login.cshtml
@page
@model WebShop.LoginModel
@{
    ViewData["Title"] = "Вход в личный кабинет";
}

@if (!ViewData.ModelState.IsValid)
{
    <div class="container" id="notif">
        <div class="notif-text" asp-validation-summary="All"></div>
        <span class="notif-close" onclick="this.parentElement.style.display='none';">&times;</span>
    </div>
}

<div class="auth-container">
    <div class="auth-logo"><a asp-page="/Index">Game Shop</a></div>
    <div class="auth-title">Вход</div>
    <form method="POST" style="flex-direction:column; justify-content:space-between; height: 240px; width: 550px" asp-page-handler="Login" asp-antiforgery="true">
        <div class="txt-input">
            <input style="width:540px; height: 55px;" asp-for="EMail" placeholder="Почта" required>
        </div>
        <div class="txt-input">
            <input style="width:540px; height: 55px;" asp-for="Password" placeholder="Пароль" required>
        </div>
        <div class="auth-btns-container">
            <div class="small-button"><a asp-page="/Registration">Регистрация</a></div>
            <div class="small-button-untext"><button style="height: inherit; width: inherit; border-radius:inherit; color:inherit; font-size:inherit; background-color: var(--button-blue);" type="submit">Вход</button></div>
        </div>
    </form>
</div>


@section Imports
{
    <link rel="stylesheet" href="~/css/dropdown.css">
    <link rel="stylesheet" href="~/css/auth.css">
    <link rel="stylesheet" href="~/css/style.css">
}

@section Page
{
    Вход в личный кабинет
}

@section MyName
{
    none
}

Pages/Profile.cshtml
@page
@model WebShop.ProfileModel
@{

}

<div class="profile-container">
    <div class="profile-menu-container">
        <div class="middle-button"><a asp-page="/Profile" style="color: white;">Профиль</a></div>
        <div class="middle-button"><a asp-page="/Basket" style="color: white;">Корзина</a></div>
        <div class="middle-button"><a asp-page="/Login" style="color: white;" asp-page-handler="Logout">Выход</a></div>
        <div class="middle-button">Удалить аккаунт</div>
    </div>
    <div class="profile-settings">

        <form method="POST" style="justify-content:space-between; height: 200px; width: 730px">
            <input style="width:485px; height: 55px;" type="text" name="name" placeholder="Имя: @ViewData["Title"]" />
            <br>
            <button class="middle-button" style="height: 60px; width: 220px;" type="submit" asp-page-handler="ChangName">Изменить</button>
        </form>
        <form method="POST" style="justify-content:space-between; height: 200px; width: 730px">
            <input style="width:485px; height: 55px;" type="text" name="email" placeholder="Почта: @User.Identity.Name" />
            <br>
            <button class="middle-button" style="height: 60px; width: 220px;" type="submit" asp-page-handler="ChangEMail">Изменить</button>
        </form>
        <form method="POST" style="justify-content:space-between; height: 310px; width: 730px">
            <div style="display: flex; flex-direction: column; justify-content: space-between; height: 135px; width: 500px">
                <input style="width: 485px; height: 55px;" type="text" name="password" placeholder="Пароль" />
                <br>
                <input style="width: 485px; height: 55px;" type="text" name="confirmPassword" placeholder="Повторите Пароль" />
            </div>
            <br>
            <button class="middle-button" style="height: 60px; width: 220px;" type="submit" asp-page-handler="ChangPassword">Изменить</button>
        </form>
    </div>
</div>

@section Imports
{
    <link rel="stylesheet" href="~/css/product.css">
    <link rel="stylesheet" href="~/css/dropdown.css">
    <link rel="stylesheet" href="~/css/profile.css">
}

@section Page
{
    Личный кабинет
}

@section MyName
{
    @ViewData["Title"]
}

Pages/PurchasePage.cshtml
@page
@model WebShop.PurchasePageModel
@{
    ViewData["Title"] = "Приобретен товар " + @Model.product.Name;
}

<div class="product-image" style="background-image: url(@Model.product.PictureUrl); margin: 0 auto"></div>
<div class="pr-title" style="margin: 0 auto; text-align: center ">Благодарим за покупку игры @Model.product.Name, ваш ключ:</div>
<h1 style="margin: 0 auto; text-align: center ">@Model.key</h1>


@section Imports
{
    <link rel="stylesheet" href="~/css/product.css">
    <link rel="stylesheet" href="~/css/dropdown.css">
}

@section Page
{
    Приобретен товар
}

@section MyName
{
    @Model.GetUserName()
}