Pages/Control/EditProduct.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebShop.Models;
using System.IO;

namespace WebShop
{
    public class EditProductModel : PageModel
    {
        private readonly WebDBContext _database;

        public Product product;
        public string codes;
        public string genres;
        public EditProductModel(WebDBContext database)
        {
            _database = database;
        }

        private string getCodesStr(int id)
        {
            var _codes = _database.Code.Where(x => x.IdProduct == id).ToArray();
            string[] arrcodes = new string[_codes.Count()];
            for (int i = 0; i < arrcodes.Count(); i++)
            {
                arrcodes[i] = _codes[i].Key;
            }
            return string.Join("\n", arrcodes);
        }

        private string getGenresStr(int id)
        {
            var Genres = _database.ProductGenre.Join(_database.Genre, p => p.IdGenre, c => c.Id, (p, c) => new { c.Name, p.IdProduct }).ToArray();
            string[] arrgenres = new string[Genres.Count()];
            for (int i = 0; i < arrgenres.Count(); i++)
            {
                if (Genres[i].IdProduct == id)
                {
                    arrgenres[i] = Genres[i].Name;
                }
            }
            arrgenres = arrgenres.Where(x => !string.IsNullOrWhiteSpace(x)).ToArray();
            return string.Join("\n", arrgenres);
        }

        public void OnGet(int id)
        {
            if (id == 0)
            {
                var lastId = _database.Product.OrderByDescending(x => x.Id).FirstOrDefault().Id;
                _database.Product.Add(new Product { Id = (short)(lastId + 1), Name = "Новый товар", Cost = 0, Description = "Новое описание", IconUrl = "", PictureUrl = "", SystemRequirements = "Новые системные требования", IdPublisher = 0, IdDeveloper = 0 });
                _database.SaveChanges();
                id = (short)(lastId + 1);
            }
            product = _database.Product.Where(x => x.Id == id).FirstOrDefault();
            codes = getCodesStr(id);
            genres = getGenresStr(id);

        }

        public void OnPostSave(string name, string cost, string description, string iconUrl, string pictureUrl, string systemRequirements, string codes, string genres, short id)
        {
            product = _database.Product.Where(x => x.Id == id).FirstOrDefault();
            if (name != null)
            {
                product.Name = name;
            }
            if (cost != null && cost.All(char.IsDigit))
            {
                product.Cost = Convert.ToInt16(cost);
            }
            if (description != null)
            {
                product.Description = description;
            }
            if (iconUrl != null)
            {
                product.IconUrl = iconUrl;
            }
            if (pictureUrl != null)
            {
                product.PictureUrl = pictureUrl;
            }
            if (systemRequirements != null)
            {
                product.SystemRequirements = systemRequirements;
            }
            if (codes != null)
            {
                var codesarr = codes.Split(new char[] { '\r', '\n' });
                codesarr = codesarr.Where(x => !string.IsNullOrWhiteSpace(x)).ToArray();              

                foreach (var e in codesarr)
                {
                    if (_database.Code.Any(p => p.Key == e) == false)
                    {
                        int lastId = _database.Code.OrderByDescending(x => x.Id).FirstOrDefault().Id;
                        _database.Code.Add(new Code { IdProduct = id, Key = e, Id = (short)(lastId + 1) });
                        _database.SaveChanges();
                    }
                }
            }
            if (genres != null)
            {
                var genresarr = genres.Split(new char[] { '\r', '\n' });
                genresarr = genresarr.Where(x => !string.IsNullOrWhiteSpace(x)).ToArray();

                Dictionary<string, int> Genres = GetGenreDict();

                foreach (var e in genresarr)
                {
                    var ganreId = Genres[e];
                    if (_database.ProductGenre.Where(x => x.IdProduct == id && x.IdGenre == ganreId).FirstOrDefault() == null)
                    {
                        _database.ProductGenre.Add(new ProductGenre { IdProduct = id, IdGenre = (short)Genres[e] });
                        _database.SaveChanges();
                    }
                }
            }        
            product.Quantity = (short)_database.Code.Count(x => x.IdProduct == id);
            _database.SaveChanges();
            OnGet(id);
        }


        private Dictionary<string, int> GetGenreDict()
        {
            Dictionary<string, int> Genres = new Dictionary<string, int>();
            foreach (var e in _database.Genre.ToArray())
            {
                Genres.Add(e.Name, e.Id);
            }
            return Genres;
        }

    }
}

Pages/Control/EditUser.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using WebShop.Models;

namespace WebShop
{
    public class EditUserModel : PageModel
    {
        private readonly WebDBContext _database;

        public User user;
        public EditUserModel(WebDBContext database)
        {
            _database = database;
        }
    
        public void OnGet(int id)
        {
            user = _database.User.Where(x => x.Id == id).FirstOrDefault();
        }

        public void OnPostSave(string name, string email, string password, int id)
        {
            user = _database.User.Where(x => x.Id == id).FirstOrDefault();
            if (name != "")
            {
                user.Name = name;
            }
            if (email != "")
            {
                user.EMail = email;
            }
            if (password != "")
            {
                user.Password = password;
            }
            _database.SaveChanges();
        }

    }
}

Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using WebShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;

namespace WebShop
{
    [ValidateAntiForgeryToken]
    public class LoginModel : PageModel
    {
        private readonly WebDBContext _database;
        public LoginModel(WebDBContext database)
        {
            _database = database;
        }


        [Required(ErrorMessage = "Не указан Email")]
        [BindProperty]
        [DataType(DataType.EmailAddress)]
        public string EMail { get; set; }

        [Required(ErrorMessage = "Не указан пароль")]
        [DataType(DataType.Password)]
        [BindProperty]
        public string Password { get; set; }

        public IActionResult OnPostLogin()
        {
            if (ModelState.IsValid)
            {
                User user = _database.User.FirstOrDefault(u => u.EMail == EMail && u.Password == Password);
                if (user != null)
                {
                    Authenticate(EMail); // аутентификация  
                }
                else
                {
                    ModelState.AddModelError("", "Некорректные логин и(или) пароль");
                    return RedirectToPage("/Login");
                }
                return RedirectToPage("/Index");
            }
            else
            {
                ModelState.AddModelError("", "Некорректные логин и(или) пароль");
                return RedirectToPage("/Login");
            }
        }
        public void OnGet()
        {
            
        }

        private Task Authenticate(string userName)
        {
            // создаем один claim
            var claims = new List<Claim>
            {
                new Claim(ClaimsIdentity.DefaultNameClaimType, userName)
            };
            // создаем объект ClaimsIdentity
            ClaimsIdentity id = new ClaimsIdentity(claims, "ApplicationCookie", ClaimsIdentity.DefaultNameClaimType, ClaimsIdentity.DefaultRoleClaimType);
            // установка аутентификационных куки
            return HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(id));
        }

        public IActionResult OnGetLogout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToPage("/Index");
        }

    }
}

Pages/Control/EditProduct.cshtml
@page
@model WebShop.EditProductModel
@{
    ViewData["Title"] = "Редактирование продукта";
}


<div class="admin-container">
    <div class="admin-menu-container">
        <div class="middle-button"><a asp-page="/Admin" asp-route-desc="users" style="color: white;">Пользователи</a></div>
        <div class="middle-button"><a asp-page="/Admin" asp-route-desc="products" style="color: white;">Товары</a></div>
        <div class="middle-button"><a asp-page="/Login" style="color: white;" asp-page-handler="Logout">Выход</a></div>
    </div>
    <div class="admin-panel" id="admin-panel">
        <form method="POST" style="display: flex; flex-direction:column; justify-content:space-between; height: 1480px; width: 600px">
            <h1>Редактирование Товара</h1>
            <br>
            <h2>Название</h2>
            <input style="width:600px; height: 60px; margin: 0 auto;" type="text" name="name" value="@Model.product.Name" />
            <br>
            <h2>Стоимость</h2>
            <input style="width:600px; height: 60px; margin: 0 auto;" type="text" name="cost" value="@Model.product.Cost" />
            <br>
            <h2>Жанры</h2>
            <textarea name="genres" rows="5" style="max-width: 600px; min-width: 600px; min-height: 100px">@Model.genres</textarea>
            <br>
            <h2>Описание</h2>
            <textarea name="description" rows="5" style="max-width: 600px; min-width: 600px; min-height: 100px">@Model.product.Description</textarea>
            <br>
            <h2>Ссылка для изображения товара в меню</h2>
            <input style="width:600px; height: 60px; margin: 0 auto;" type="text" name="iconUrl" value="@Model.product.IconUrl" />
            <br>
            <h2>Ссылка для изображения товара на страние</h2>
            <input style="width:600px; height: 60px; margin: 0 auto;" type="text" name="pictureUrl" value="@Model.product.PictureUrl" />
            <br>
            <h2>Системные требования</h2>
            <textarea name="systemRequirements" rows="5" style="max-width: 600px; min-width: 600px; min-height: 100px">@Model.product.SystemRequirements</textarea>
            <br>
            <h2>Список ключей</h2>
            <textarea name="codes" rows="5" style="max-width: 600px; min-width: 600px; min-height: 100px">@Model.codes</textarea>
            <br>
            <button class="middle-button" style="height: 60px; width: 220px;" type="submit" asp-route-id="@Model.product.Id" asp-page-handler="Save">Сохранить</button>
        </form>
    </div>
</div>

@section Imports
{
    <link rel="stylesheet" href="~/css/admin.css">
    <link rel="stylesheet" href="~/css/dropdown.css">
}

@section Page
{
    Редактирование продукта
}

@section MyName
{
    Admin
}

Pages/Control/EditUser.cshtml
@page
@model WebShop.EditUserModel
@{
    ViewData["Title"] = "Редактирование пользователя";
}

<div class="admin-container">
    <div class="admin-menu-container">
        <div class="middle-button"><a asp-page="/Admin" asp-route-desc="users" style="color: white;">Пользователи</a></div>
        <div class="middle-button"><a asp-page="/Admin" asp-route-desc="products" style="color: white;">Товары</a></div>
        <div class="middle-button"><a asp-page="/Login" style="color: white;" asp-page-handler="Logout">Выход</a></div>
    </div>
    <div class="admin-panel" id="admin-panel">
        <form method="POST" style="display: flex; flex-direction:column; justify-content:space-between; height: 580px; width: 600px">
            <h1>Редактирование пользователя</h1>
            <br>
            <h2>Имя</h2>
            <input style="width:600px; height: 60px; margin: 0 auto;" type="text" name="name" value="@Model.user.Name" placeholder="Имя" />
            <br>
            <h2>Почта</h2>
            <input style="width:600px; height: 60px; margin: 0 auto;" type="text" name="email" value="@Model.user.EMail" placeholder="Почта" />
            <br>
            <h2>Пароль</h2>
            <input style="width:600px; height: 60px; margin: 0 auto;" type="text" name="password" value="@Model.user.Password" placeholder="Пароль" />
            <br>
            <button class="middle-button" style="height: 60px; width: 220px;" type="submit" asp-route-id="@Model.user.Id" asp-page-handler="Save">Сохранить</button>
        </form>
    </div>
</div>

@section Imports
{
    <link rel="stylesheet" href="~/css/admin.css">
    <link rel="stylesheet" href="~/css/dropdown.css">
}

@section Page
{
    Редактирование пользователя
}

@section MyName
{
    Admin
}